### PR TITLE
BD-1069:Compliance Issues in Lightning-VOD-example

### PR DESCRIPTION
**Pull request by BhargaviPalineni79**

### CODE REVIEW

**Comment by mhughesacn** [comment]
Hi Bhargavi:

- NOTICE needs to refer to Metrological, not Comcast.
- tmdb-logo.png - please don't delete this.  Metrological will have to have to decide what to do.
- Please change src/App.js to update the path for the montserrat font files that you have moved.

Thanks

**Comment by mhughesacn** [comment]
Hi Bhargavi: Any reason src/pages/Player.js isn't updated?  Thanks.

**Comment by BhargaviPalineni79** [comment]
Oh Sorry, I think I missed it. Updated the file now.

**Comment by mhughesacn** [comment]
Now fixed - thanks Bhargavi

**Review by wouterlucas — APPROVED** [review]
LGTM

**Pull request merged**
